// app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { cookies } from "next/headers";
import { LanguageProvider } from "@/components/language-provider";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { TopBar } from "@/components/top-bar";
import { DynamicBreadcrumbs } from "@/components/dynamic-breadcrumbs";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { cn } from "@/lib/utils"; // Impor cn jika belum ada

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "Luminite - %s",
    default: "Luminite",
  },
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover" as const,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const initialLang = (cookieStore.get("lang")?.value as "en" | "id") || "en";
  return (
    // [PERBAIKAN] Tambahkan className="h-full" di sini
    <html lang={initialLang} className="h-full overflow-x-hidden" suppressHydrationWarning>
      <body
        // [PERBAIKAN] Tambahkan h-full, bg-background, dan gabungkan kelas dengan `cn`
        className={cn(
          "h-full bg-background font-sans antialiased overflow-x-hidden",
          geistSans.variable,
          geistMono.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LanguageProvider initialLang={initialLang}>
            <SidebarProvider>
              <AppSidebar />
              <SidebarInset className="flex flex-col h-screen overflow-hidden">
                <TopBar>
                  <DynamicBreadcrumbs />
                </TopBar>
                <main className="flex-1 overflow-y-auto overflow-x-hidden">
                  {children}
                </main>
              </SidebarInset>
              <Toaster richColors position="top-right" />
            </SidebarProvider>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}